### ISSUE TITLE
Complete Seeding script

### ISSUE THREAD

**Issue by SebastianKuesters** [wemogy/spaceblocks-sample-helloworld#1]
- [x] Create static roles via API (https://docs.spaceblocks.cloud/permissions/concepts/role#create-a-built-in-role)
- [x] Create resource type via API (https://docs.spaceblocks.cloud/permissions/concepts/resource-type#create-a-resource-type)
- [x] Add permissions to the resource type via API (https://docs.spaceblocks.cloud/permissions/concepts/permission#manage-permissions)

**Comment by robinmanuelthiel** [comment]
Please use a separate `setup.sh` script for these things, as the Blog Posts, that reference on this repo create these resources in the portal

**Comment by bennetrr** [comment]
@robinmanuelthiel Can you give me a link to the blog post where this repo is used?

**Comment by robinmanuelthiel** [comment]
https://www.spaceblocks.cloud/blog/quickly-add-permission-checks-to-your-asp-net-apps

**Comment by robinmanuelthiel** [comment]
@bennetrr This is "In Review" but I can't find a PR? What is to be reviewed...
